# Generated by Django 4.2 on 2024-02-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField(null=True)),
                ('file', models.FileField(blank=True, upload_to='uploads/message/')),
                ('flyer', models.ImageField(blank=True, upload_to='uploads/message_flyer/')),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
                ('uploader', models.CharField(max_length=50)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to='core.series')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
